### PR TITLE
Fix #30: Added login page

### LINKED ISSUE #30: Adding Login Page 👾 [FrontEnd]
## Login Page (Make it interactive ⚡ and minimal 🐼)
Heading -
```
Welcome!
```
Sub Heading -
```
Sign in to your account
```
## Login Page Must
```
- Be Responsive
- Have Illustration
```

## Form
```
- Username [Required Input]
- Password [Required Input]
- Forget password [Link] 
- Login [Button]
```
## After Form
```
- Create your account ! [Link]
- Social Icons
  - GitHub [Link]
  - Discord [Link]
  - LinkedIn [Link]
```

### PR DESCRIPTION
**Pull request by Shivangi-ch**
## Explanation

I have added a login page.

## Type of Change:

- Code
- Quality Assurance
- User Interface

## Checklist

- [x] The PR title starts with "Fix #bugnum: "followed by a short, clear summary of the changes. ( If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...")
- [x] The PR explanation includes the words "Fixes #bugnum: ..." ( or "Fixes part of #bugnum" if the PR only partially fixes an issue ).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adhere to the contributing guidelines of the project.
- [x] The PR is raised for an issue that has been assigned to you.
- [x] The PR is made to the branch that's **called** "develop".
- [x] The PR is raised from a branch that is up-to-date with "develop".
Screenshot from 2021-05-08 02-23-59

### CODE REVIEW

**Review by 5tupidbrain — CHANGES_REQUESTED** [review]
# Changes Requested

```
- Add some background 
- Make the box-shadow smoother (Hint: Use multi-layer shadow)
- Reduce the X-axis padding from input
- Make the Login Button Centered
- Use the same icons from footer
- Add Heading "Welcome"
- Make the Subheading smaller "Sign in to your account"
- Add Padding to #loginform
```
# Code Changes
```
- Don't use className row in the input box it is conflicting with Bootstrap,
  and making the Input container overflow outside the #loginform.
- Use FlexBox to center the Login button or just use FlexBox in #loginform>div.
- Most of the div's are overflowing Fix that!
- Use FLexBox to give structure and align items.
```

**Comment by Shivangi-ch** [comment]
@5tupidbrain I have made the requested changes.
Screenshot from 2021-05-10 14-43-15

**Comment by Shivangi-ch** [comment]
I spent a lot of time on this, if you like the work i requested you to make it `level3`.

**Comment by Shivangi-ch** [comment]
Hey @5tupidbrain . It is in center for every size.
U can see in the gif below.
dfrgtry

**Comment by Shivangi-ch** [comment]
@5tupidbrain I have tried to fix this . 
Hnet-imawderege
If  any item still overflows ,I will try to fix it  later  in another Pr. Currently I am working on the landing page of this website ,Once I am done with it. I will try this.Till then Please merge this.

**Comment by Shivangi-ch** [comment]
Hey @5tupidbrain Please Review!

**Comment by 5tupidbrain** [comment]
I find the issue for not center aligned is that you are not hiding the div `illustration_img`  instead hiding the image inside it.! 
And `illustration_img`  is consider as BlockElement and FLEX align the elements according to that. [Total Child element became 2]

**Comment by Shivangi-ch** [comment]
Thanks, i understood it now!

**Pull request merged**
