### PR TITLE
Fix #38: Added Forgot Password Page [FrontEnd]

### LINKED ISSUE #38: Adding Forgot Password Page [Front-End]
@5tupidbrain @riturajjain2000 Kindly assign this issue to me.

### PR DESCRIPTION
**Pull request by Saatvik21**
## Explanation

I've added a Forgot Password page (FrontEnd).
Fixes #38 

## Type of Change:

- Code
- Quality Assurance
- User Interface

## Checklist

- [x] The PR title starts with "Fix #bugnum: "followed by a short, clear summary of the changes. ( If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...")
- [x] The PR explanation includes the words "Fixes #bugnum: ..." ( or "Fixes part of #bugnum" if the PR only partially fixes an issue ).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adhere to the contributing guidelines of the project.
- [x] The PR is raised for an issue that has been assigned to you.
- [x] The PR is made to the branch that's **called** "develop".
- [x] The PR is raised from a branch that is up-to-date with "develop".

## Screenshot 
Screenshot_1

### CODE REVIEW

**Comment by Saatvik21** [comment]
@5tupidbrain @riturajjain2000 Please review!

**Comment by 5tupidbrain** [comment]
# Changes

```
 - Add padding in input field
 - Fix the Image
 - Center the form in mobile view
```


## Fix the Image
image
image

## Center the form
image

**Review by 5tupidbrain — CHANGES_REQUESTED** [review]
# Changes

```
 - Add padding in input field
 - Fix the Image
 - Center the form in mobile view
```


## Fix the Image
image
image

## Center the form
image

**Comment by Saatvik21** [comment]
@5tupidbrain I've done the required changes. 

Let me know if there's still any error.

**Review by 5tupidbrain — CHANGES_REQUESTED** [review]
## Changes

```
- Still not centered
- add min-height
```

### Center
image

### Min-Height
image
image

**Comment by Saatvik21** [comment]
I've made the changes, please review!

**Comment by Saatvik21** [comment]
@5tupidbrain Please add the labels as well!

**Pull request merged**
